spring:
  application:
    name: sa-crud
  h2:
    console:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://sa-eureka:8761/eureka/,
                   http://localhost:8761/eureka/
